### ISSUE TITLE
Unknown database type geometry requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

### ISSUE THREAD

**Issue by thomaxxl** [jawira/mysql-draw#9]
`Unknown database type geometry requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.`

I use the [sakila test database](https://dev.mysql.com/doc/sakila/en/), haven't tried other dbs

**Comment by jawira** [comment]
Hi, thanks for reporting this. I have updated mysql-draw and now it's compatible with sakila db.

Can you try https://github.com/jawira/mysql-draw/releases/download/v0.1.2/mysql-draw.phar

Thank you
